// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/infra/primary/grpc/order/request/order.proto

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OrderNumber           string                 `protobuf:"bytes,1,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	ExternalOrderId       string                 `protobuf:"bytes,2,opt,name=external_order_id,json=externalOrderId,proto3" json:"external_order_id,omitempty"`
	BusinessId            string                 `protobuf:"bytes,3,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	IntegrationTypeId     int32                  `protobuf:"varint,4,opt,name=integration_type_id,json=integrationTypeId,proto3" json:"integration_type_id,omitempty"`
	ExternalIntegrationId int32                  `protobuf:"varint,5,opt,name=external_integration_id,json=externalIntegrationId,proto3" json:"external_integration_id,omitempty"`
	OrderTypeId           uint32                 `protobuf:"varint,6,opt,name=order_type_id,json=orderTypeId,proto3" json:"order_type_id,omitempty"`
	TotalShipment         float64                `protobuf:"fixed64,7,opt,name=total_shipment,json=totalShipment,proto3" json:"total_shipment,omitempty"`
	TrackingNumber        string                 `protobuf:"bytes,8,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	PaymentMethodId       int32                  `protobuf:"varint,9,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	PaymentTypeRaw        string                 `protobuf:"bytes,10,opt,name=payment_type_raw,json=paymentTypeRaw,proto3" json:"payment_type_raw,omitempty"`
	PaymentTypeId         int32                  `protobuf:"varint,11,opt,name=payment_type_id,json=paymentTypeId,proto3" json:"payment_type_id,omitempty"`
	CountryId             int32                  `protobuf:"varint,12,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	CountryNameRaw        string                 `protobuf:"bytes,13,opt,name=country_name_raw,json=countryNameRaw,proto3" json:"country_name_raw,omitempty"`
	WarehouseId           int32                  `protobuf:"varint,14,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	ExtraData             *_struct.Struct        `protobuf:"bytes,15,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	Customer              *CreateCustomerOrder   `protobuf:"bytes,16,opt,name=customer,proto3" json:"customer,omitempty"`
	Shipping              *CreateShippingOrder   `protobuf:"bytes,17,opt,name=shipping,proto3" json:"shipping,omitempty"`
	OriginShipping        *CreateShippingOrder   `protobuf:"bytes,18,opt,name=origin_shipping,json=originShipping,proto3" json:"origin_shipping,omitempty"`
	Items                 []*ProductOrderReq     `protobuf:"bytes,19,rep,name=items,proto3" json:"items,omitempty"`
	Notes                 []string               `protobuf:"bytes,20,rep,name=notes,proto3" json:"notes,omitempty"`
	CodTotal              float64                `protobuf:"fixed64,21,opt,name=cod_total,json=codTotal,proto3" json:"cod_total,omitempty"`
	DeliveryDate          *timestamp.Timestamp   `protobuf:"bytes,22,opt,name=delivery_date,json=deliveryDate,proto3" json:"delivery_date,omitempty"`
	Coupon                string                 `protobuf:"bytes,23,opt,name=coupon,proto3" json:"coupon,omitempty"`
	Discount              float64                `protobuf:"fixed64,24,opt,name=discount,proto3" json:"discount,omitempty"`
	Total                 float64                `protobuf:"fixed64,25,opt,name=total,proto3" json:"total,omitempty"`
	Boxes                 int32                  `protobuf:"varint,26,opt,name=boxes,proto3" json:"boxes,omitempty"`
	IsLastMile            bool                   `protobuf:"varint,27,opt,name=is_last_mile,json=isLastMile,proto3" json:"is_last_mile,omitempty"`
	Invoiceable           bool                   `protobuf:"varint,28,opt,name=invoiceable,proto3" json:"invoiceable,omitempty"`
	OrderStatusId         int32                  `protobuf:"varint,29,opt,name=order_status_id,json=orderStatusId,proto3" json:"order_status_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_internal_infra_primary_grpc_order_request_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_primary_grpc_order_request_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_internal_infra_primary_grpc_order_request_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *CreateOrderRequest) GetExternalOrderId() string {
	if x != nil {
		return x.ExternalOrderId
	}
	return ""
}

func (x *CreateOrderRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *CreateOrderRequest) GetIntegrationTypeId() int32 {
	if x != nil {
		return x.IntegrationTypeId
	}
	return 0
}

func (x *CreateOrderRequest) GetExternalIntegrationId() int32 {
	if x != nil {
		return x.ExternalIntegrationId
	}
	return 0
}

func (x *CreateOrderRequest) GetOrderTypeId() uint32 {
	if x != nil {
		return x.OrderTypeId
	}
	return 0
}

func (x *CreateOrderRequest) GetTotalShipment() float64 {
	if x != nil {
		return x.TotalShipment
	}
	return 0
}

func (x *CreateOrderRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *CreateOrderRequest) GetPaymentMethodId() int32 {
	if x != nil {
		return x.PaymentMethodId
	}
	return 0
}

func (x *CreateOrderRequest) GetPaymentTypeRaw() string {
	if x != nil {
		return x.PaymentTypeRaw
	}
	return ""
}

func (x *CreateOrderRequest) GetPaymentTypeId() int32 {
	if x != nil {
		return x.PaymentTypeId
	}
	return 0
}

func (x *CreateOrderRequest) GetCountryId() int32 {
	if x != nil {
		return x.CountryId
	}
	return 0
}

func (x *CreateOrderRequest) GetCountryNameRaw() string {
	if x != nil {
		return x.CountryNameRaw
	}
	return ""
}

func (x *CreateOrderRequest) GetWarehouseId() int32 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *CreateOrderRequest) GetExtraData() *_struct.Struct {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *CreateOrderRequest) GetCustomer() *CreateCustomerOrder {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *CreateOrderRequest) GetShipping() *CreateShippingOrder {
	if x != nil {
		return x.Shipping
	}
	return nil
}

func (x *CreateOrderRequest) GetOriginShipping() *CreateShippingOrder {
	if x != nil {
		return x.OriginShipping
	}
	return nil
}

func (x *CreateOrderRequest) GetItems() []*ProductOrderReq {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateOrderRequest) GetNotes() []string {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *CreateOrderRequest) GetCodTotal() float64 {
	if x != nil {
		return x.CodTotal
	}
	return 0
}

func (x *CreateOrderRequest) GetDeliveryDate() *timestamp.Timestamp {
	if x != nil {
		return x.DeliveryDate
	}
	return nil
}

func (x *CreateOrderRequest) GetCoupon() string {
	if x != nil {
		return x.Coupon
	}
	return ""
}

func (x *CreateOrderRequest) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *CreateOrderRequest) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CreateOrderRequest) GetBoxes() int32 {
	if x != nil {
		return x.Boxes
	}
	return 0
}

func (x *CreateOrderRequest) GetIsLastMile() bool {
	if x != nil {
		return x.IsLastMile
	}
	return false
}

func (x *CreateOrderRequest) GetInvoiceable() bool {
	if x != nil {
		return x.Invoiceable
	}
	return false
}

func (x *CreateOrderRequest) GetOrderStatusId() int32 {
	if x != nil {
		return x.OrderStatusId
	}
	return 0
}

type CreateCustomerOrder struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FullName          string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	MobilePhoneNumber string                 `protobuf:"bytes,2,opt,name=mobile_phone_number,json=mobilePhoneNumber,proto3" json:"mobile_phone_number,omitempty"`
	DocumentTypeId    int32                  `protobuf:"varint,3,opt,name=document_type_id,json=documentTypeId,proto3" json:"document_type_id,omitempty"`
	Dni               string                 `protobuf:"bytes,4,opt,name=dni,proto3" json:"dni,omitempty"`
	Email             string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateCustomerOrder) Reset() {
	*x = CreateCustomerOrder{}
	mi := &file_internal_infra_primary_grpc_order_request_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerOrder) ProtoMessage() {}

func (x *CreateCustomerOrder) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_primary_grpc_order_request_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerOrder.ProtoReflect.Descriptor instead.
func (*CreateCustomerOrder) Descriptor() ([]byte, []int) {
	return file_internal_infra_primary_grpc_order_request_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCustomerOrder) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateCustomerOrder) GetMobilePhoneNumber() string {
	if x != nil {
		return x.MobilePhoneNumber
	}
	return ""
}

func (x *CreateCustomerOrder) GetDocumentTypeId() int32 {
	if x != nil {
		return x.DocumentTypeId
	}
	return 0
}

func (x *CreateCustomerOrder) GetDni() string {
	if x != nil {
		return x.Dni
	}
	return ""
}

func (x *CreateCustomerOrder) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateShippingOrder struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Country           string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	State             string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	City              string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Address           string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	AddressLine       string                 `protobuf:"bytes,5,opt,name=address_line,json=addressLine,proto3" json:"address_line,omitempty"`
	MobilePhoneNumber string                 `protobuf:"bytes,6,opt,name=mobile_phone_number,json=mobilePhoneNumber,proto3" json:"mobile_phone_number,omitempty"`
	FullName          string                 `protobuf:"bytes,7,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Zip               string                 `protobuf:"bytes,8,opt,name=zip,proto3" json:"zip,omitempty"`
	Lat               *wrappers.DoubleValue  `protobuf:"bytes,9,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng               *wrappers.DoubleValue  `protobuf:"bytes,10,opt,name=lng,proto3" json:"lng,omitempty"`
	CityDaneId        *wrappers.Int32Value   `protobuf:"bytes,11,opt,name=city_dane_id,json=cityDaneId,proto3" json:"city_dane_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateShippingOrder) Reset() {
	*x = CreateShippingOrder{}
	mi := &file_internal_infra_primary_grpc_order_request_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShippingOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShippingOrder) ProtoMessage() {}

func (x *CreateShippingOrder) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_primary_grpc_order_request_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShippingOrder.ProtoReflect.Descriptor instead.
func (*CreateShippingOrder) Descriptor() ([]byte, []int) {
	return file_internal_infra_primary_grpc_order_request_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShippingOrder) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateShippingOrder) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateShippingOrder) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateShippingOrder) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateShippingOrder) GetAddressLine() string {
	if x != nil {
		return x.AddressLine
	}
	return ""
}

func (x *CreateShippingOrder) GetMobilePhoneNumber() string {
	if x != nil {
		return x.MobilePhoneNumber
	}
	return ""
}

func (x *CreateShippingOrder) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateShippingOrder) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

func (x *CreateShippingOrder) GetLat() *wrappers.DoubleValue {
	if x != nil {
		return x.Lat
	}
	return nil
}

func (x *CreateShippingOrder) GetLng() *wrappers.DoubleValue {
	if x != nil {
		return x.Lng
	}
	return nil
}

func (x *CreateShippingOrder) GetCityDaneId() *wrappers.Int32Value {
	if x != nil {
		return x.CityDaneId
	}
	return nil
}

type ProductOrderReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductId         *wrappers.StringValue  `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Sku               *wrappers.StringValue  `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	ExternalId        *wrappers.StringValue  `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Ean               *wrappers.StringValue  `protobuf:"bytes,4,opt,name=ean,proto3" json:"ean,omitempty"`
	Name              string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Notes             *wrappers.StringValue  `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	Large             *wrappers.DoubleValue  `protobuf:"bytes,7,opt,name=large,proto3" json:"large,omitempty"`
	Width             *wrappers.DoubleValue  `protobuf:"bytes,8,opt,name=width,proto3" json:"width,omitempty"`
	Weight            *wrappers.DoubleValue  `protobuf:"bytes,9,opt,name=weight,proto3" json:"weight,omitempty"`
	Height            *wrappers.DoubleValue  `protobuf:"bytes,10,opt,name=height,proto3" json:"height,omitempty"`
	MeasurementUnitId int64                  `protobuf:"varint,11,opt,name=measurement_unit_id,json=measurementUnitId,proto3" json:"measurement_unit_id,omitempty"`
	Description       string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	Quantity          int32                  `protobuf:"varint,13,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price             float64                `protobuf:"fixed64,14,opt,name=price,proto3" json:"price,omitempty"`
	Discount          float64                `protobuf:"fixed64,15,opt,name=discount,proto3" json:"discount,omitempty"`
	Tax               *wrappers.DoubleValue  `protobuf:"bytes,16,opt,name=tax,proto3" json:"tax,omitempty"`
	Items             []*ProductOrderReq     `protobuf:"bytes,17,rep,name=items,proto3" json:"items,omitempty"`
	IsCustomKit       bool                   `protobuf:"varint,18,opt,name=is_custom_kit,json=isCustomKit,proto3" json:"is_custom_kit,omitempty"`
	Active            bool                   `protobuf:"varint,19,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProductOrderReq) Reset() {
	*x = ProductOrderReq{}
	mi := &file_internal_infra_primary_grpc_order_request_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductOrderReq) ProtoMessage() {}

func (x *ProductOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_primary_grpc_order_request_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductOrderReq.ProtoReflect.Descriptor instead.
func (*ProductOrderReq) Descriptor() ([]byte, []int) {
	return file_internal_infra_primary_grpc_order_request_order_proto_rawDescGZIP(), []int{3}
}

func (x *ProductOrderReq) GetProductId() *wrappers.StringValue {
	if x != nil {
		return x.ProductId
	}
	return nil
}

func (x *ProductOrderReq) GetSku() *wrappers.StringValue {
	if x != nil {
		return x.Sku
	}
	return nil
}

func (x *ProductOrderReq) GetExternalId() *wrappers.StringValue {
	if x != nil {
		return x.ExternalId
	}
	return nil
}

func (x *ProductOrderReq) GetEan() *wrappers.StringValue {
	if x != nil {
		return x.Ean
	}
	return nil
}

func (x *ProductOrderReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductOrderReq) GetNotes() *wrappers.StringValue {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *ProductOrderReq) GetLarge() *wrappers.DoubleValue {
	if x != nil {
		return x.Large
	}
	return nil
}

func (x *ProductOrderReq) GetWidth() *wrappers.DoubleValue {
	if x != nil {
		return x.Width
	}
	return nil
}

func (x *ProductOrderReq) GetWeight() *wrappers.DoubleValue {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *ProductOrderReq) GetHeight() *wrappers.DoubleValue {
	if x != nil {
		return x.Height
	}
	return nil
}

func (x *ProductOrderReq) GetMeasurementUnitId() int64 {
	if x != nil {
		return x.MeasurementUnitId
	}
	return 0
}

func (x *ProductOrderReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductOrderReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ProductOrderReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductOrderReq) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *ProductOrderReq) GetTax() *wrappers.DoubleValue {
	if x != nil {
		return x.Tax
	}
	return nil
}

func (x *ProductOrderReq) GetItems() []*ProductOrderReq {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ProductOrderReq) GetIsCustomKit() bool {
	if x != nil {
		return x.IsCustomKit
	}
	return false
}

func (x *ProductOrderReq) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

var File_internal_infra_primary_grpc_order_request_order_proto protoreflect.FileDescriptor

const file_internal_infra_primary_grpc_order_request_order_proto_rawDesc = "" +
	"\n" +
	"5internal/infra/primary/grpc/order/request/order.proto\x12\arequest\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xad\t\n" +
	"\x12CreateOrderRequest\x12!\n" +
	"\forder_number\x18\x01 \x01(\tR\vorderNumber\x12*\n" +
	"\x11external_order_id\x18\x02 \x01(\tR\x0fexternalOrderId\x12\x1f\n" +
	"\vbusiness_id\x18\x03 \x01(\tR\n" +
	"businessId\x12.\n" +
	"\x13integration_type_id\x18\x04 \x01(\x05R\x11integrationTypeId\x126\n" +
	"\x17external_integration_id\x18\x05 \x01(\x05R\x15externalIntegrationId\x12\"\n" +
	"\rorder_type_id\x18\x06 \x01(\rR\vorderTypeId\x12%\n" +
	"\x0etotal_shipment\x18\a \x01(\x01R\rtotalShipment\x12'\n" +
	"\x0ftracking_number\x18\b \x01(\tR\x0etrackingNumber\x12*\n" +
	"\x11payment_method_id\x18\t \x01(\x05R\x0fpaymentMethodId\x12(\n" +
	"\x10payment_type_raw\x18\n" +
	" \x01(\tR\x0epaymentTypeRaw\x12&\n" +
	"\x0fpayment_type_id\x18\v \x01(\x05R\rpaymentTypeId\x12\x1d\n" +
	"\n" +
	"country_id\x18\f \x01(\x05R\tcountryId\x12(\n" +
	"\x10country_name_raw\x18\r \x01(\tR\x0ecountryNameRaw\x12!\n" +
	"\fwarehouse_id\x18\x0e \x01(\x05R\vwarehouseId\x126\n" +
	"\n" +
	"extra_data\x18\x0f \x01(\v2\x17.google.protobuf.StructR\textraData\x128\n" +
	"\bcustomer\x18\x10 \x01(\v2\x1c.request.CreateCustomerOrderR\bcustomer\x128\n" +
	"\bshipping\x18\x11 \x01(\v2\x1c.request.CreateShippingOrderR\bshipping\x12E\n" +
	"\x0forigin_shipping\x18\x12 \x01(\v2\x1c.request.CreateShippingOrderR\x0eoriginShipping\x12.\n" +
	"\x05items\x18\x13 \x03(\v2\x18.request.ProductOrderReqR\x05items\x12\x14\n" +
	"\x05notes\x18\x14 \x03(\tR\x05notes\x12\x1b\n" +
	"\tcod_total\x18\x15 \x01(\x01R\bcodTotal\x12?\n" +
	"\rdelivery_date\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\fdeliveryDate\x12\x16\n" +
	"\x06coupon\x18\x17 \x01(\tR\x06coupon\x12\x1a\n" +
	"\bdiscount\x18\x18 \x01(\x01R\bdiscount\x12\x14\n" +
	"\x05total\x18\x19 \x01(\x01R\x05total\x12\x14\n" +
	"\x05boxes\x18\x1a \x01(\x05R\x05boxes\x12 \n" +
	"\fis_last_mile\x18\x1b \x01(\bR\n" +
	"isLastMile\x12 \n" +
	"\vinvoiceable\x18\x1c \x01(\bR\vinvoiceable\x12&\n" +
	"\x0forder_status_id\x18\x1d \x01(\x05R\rorderStatusId\"\xb4\x01\n" +
	"\x13CreateCustomerOrder\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12.\n" +
	"\x13mobile_phone_number\x18\x02 \x01(\tR\x11mobilePhoneNumber\x12(\n" +
	"\x10document_type_id\x18\x03 \x01(\x05R\x0edocumentTypeId\x12\x10\n" +
	"\x03dni\x18\x04 \x01(\tR\x03dni\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\"\x94\x03\n" +
	"\x13CreateShippingOrder\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12!\n" +
	"\faddress_line\x18\x05 \x01(\tR\vaddressLine\x12.\n" +
	"\x13mobile_phone_number\x18\x06 \x01(\tR\x11mobilePhoneNumber\x12\x1b\n" +
	"\tfull_name\x18\a \x01(\tR\bfullName\x12\x10\n" +
	"\x03zip\x18\b \x01(\tR\x03zip\x12.\n" +
	"\x03lat\x18\t \x01(\v2\x1c.google.protobuf.DoubleValueR\x03lat\x12.\n" +
	"\x03lng\x18\n" +
	" \x01(\v2\x1c.google.protobuf.DoubleValueR\x03lng\x12=\n" +
	"\fcity_dane_id\x18\v \x01(\v2\x1b.google.protobuf.Int32ValueR\n" +
	"cityDaneId\"\xc5\x06\n" +
	"\x0fProductOrderReq\x12;\n" +
	"\n" +
	"product_id\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\tproductId\x12.\n" +
	"\x03sku\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x03sku\x12=\n" +
	"\vexternal_id\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"externalId\x12.\n" +
	"\x03ean\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x03ean\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x122\n" +
	"\x05notes\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x05notes\x122\n" +
	"\x05large\x18\a \x01(\v2\x1c.google.protobuf.DoubleValueR\x05large\x122\n" +
	"\x05width\x18\b \x01(\v2\x1c.google.protobuf.DoubleValueR\x05width\x124\n" +
	"\x06weight\x18\t \x01(\v2\x1c.google.protobuf.DoubleValueR\x06weight\x124\n" +
	"\x06height\x18\n" +
	" \x01(\v2\x1c.google.protobuf.DoubleValueR\x06height\x12.\n" +
	"\x13measurement_unit_id\x18\v \x01(\x03R\x11measurementUnitId\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12\x1a\n" +
	"\bquantity\x18\r \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x0e \x01(\x01R\x05price\x12\x1a\n" +
	"\bdiscount\x18\x0f \x01(\x01R\bdiscount\x12.\n" +
	"\x03tax\x18\x10 \x01(\v2\x1c.google.protobuf.DoubleValueR\x03tax\x12.\n" +
	"\x05items\x18\x11 \x03(\v2\x18.request.ProductOrderReqR\x05items\x12\"\n" +
	"\ris_custom_kit\x18\x12 \x01(\bR\visCustomKit\x12\x16\n" +
	"\x06active\x18\x13 \x01(\bR\x06active2R\n" +
	"\fOrderService\x12B\n" +
	"\vCreateOrder\x12\x1b.request.CreateOrderRequest\x1a\x16.google.protobuf.EmptyBBZ@engine-central/internal/infra/primary/grpc/order/request;requestb\x06proto3"

var (
	file_internal_infra_primary_grpc_order_request_order_proto_rawDescOnce sync.Once
	file_internal_infra_primary_grpc_order_request_order_proto_rawDescData []byte
)

func file_internal_infra_primary_grpc_order_request_order_proto_rawDescGZIP() []byte {
	file_internal_infra_primary_grpc_order_request_order_proto_rawDescOnce.Do(func() {
		file_internal_infra_primary_grpc_order_request_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infra_primary_grpc_order_request_order_proto_rawDesc), len(file_internal_infra_primary_grpc_order_request_order_proto_rawDesc)))
	})
	return file_internal_infra_primary_grpc_order_request_order_proto_rawDescData
}

var file_internal_infra_primary_grpc_order_request_order_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_infra_primary_grpc_order_request_order_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),   // 0: request.CreateOrderRequest
	(*CreateCustomerOrder)(nil),  // 1: request.CreateCustomerOrder
	(*CreateShippingOrder)(nil),  // 2: request.CreateShippingOrder
	(*ProductOrderReq)(nil),      // 3: request.ProductOrderReq
	(*_struct.Struct)(nil),       // 4: google.protobuf.Struct
	(*timestamp.Timestamp)(nil),  // 5: google.protobuf.Timestamp
	(*wrappers.DoubleValue)(nil), // 6: google.protobuf.DoubleValue
	(*wrappers.Int32Value)(nil),  // 7: google.protobuf.Int32Value
	(*wrappers.StringValue)(nil), // 8: google.protobuf.StringValue
	(*empty.Empty)(nil),          // 9: google.protobuf.Empty
}
var file_internal_infra_primary_grpc_order_request_order_proto_depIdxs = []int32{
	4,  // 0: request.CreateOrderRequest.extra_data:type_name -> google.protobuf.Struct
	1,  // 1: request.CreateOrderRequest.customer:type_name -> request.CreateCustomerOrder
	2,  // 2: request.CreateOrderRequest.shipping:type_name -> request.CreateShippingOrder
	2,  // 3: request.CreateOrderRequest.origin_shipping:type_name -> request.CreateShippingOrder
	3,  // 4: request.CreateOrderRequest.items:type_name -> request.ProductOrderReq
	5,  // 5: request.CreateOrderRequest.delivery_date:type_name -> google.protobuf.Timestamp
	6,  // 6: request.CreateShippingOrder.lat:type_name -> google.protobuf.DoubleValue
	6,  // 7: request.CreateShippingOrder.lng:type_name -> google.protobuf.DoubleValue
	7,  // 8: request.CreateShippingOrder.city_dane_id:type_name -> google.protobuf.Int32Value
	8,  // 9: request.ProductOrderReq.product_id:type_name -> google.protobuf.StringValue
	8,  // 10: request.ProductOrderReq.sku:type_name -> google.protobuf.StringValue
	8,  // 11: request.ProductOrderReq.external_id:type_name -> google.protobuf.StringValue
	8,  // 12: request.ProductOrderReq.ean:type_name -> google.protobuf.StringValue
	8,  // 13: request.ProductOrderReq.notes:type_name -> google.protobuf.StringValue
	6,  // 14: request.ProductOrderReq.large:type_name -> google.protobuf.DoubleValue
	6,  // 15: request.ProductOrderReq.width:type_name -> google.protobuf.DoubleValue
	6,  // 16: request.ProductOrderReq.weight:type_name -> google.protobuf.DoubleValue
	6,  // 17: request.ProductOrderReq.height:type_name -> google.protobuf.DoubleValue
	6,  // 18: request.ProductOrderReq.tax:type_name -> google.protobuf.DoubleValue
	3,  // 19: request.ProductOrderReq.items:type_name -> request.ProductOrderReq
	0,  // 20: request.OrderService.CreateOrder:input_type -> request.CreateOrderRequest
	9,  // 21: request.OrderService.CreateOrder:output_type -> google.protobuf.Empty
	21, // [21:22] is the sub-list for method output_type
	20, // [20:21] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_internal_infra_primary_grpc_order_request_order_proto_init() }
func file_internal_infra_primary_grpc_order_request_order_proto_init() {
	if File_internal_infra_primary_grpc_order_request_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infra_primary_grpc_order_request_order_proto_rawDesc), len(file_internal_infra_primary_grpc_order_request_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infra_primary_grpc_order_request_order_proto_goTypes,
		DependencyIndexes: file_internal_infra_primary_grpc_order_request_order_proto_depIdxs,
		MessageInfos:      file_internal_infra_primary_grpc_order_request_order_proto_msgTypes,
	}.Build()
	File_internal_infra_primary_grpc_order_request_order_proto = out.File
	file_internal_infra_primary_grpc_order_request_order_proto_goTypes = nil
	file_internal_infra_primary_grpc_order_request_order_proto_depIdxs = nil
}
